[language-server.shader-language-server]
command = "shader-language-server"
args = [ "--stdio", "--hlsl" ]

[[language]]
name = "hlsl"
scope = "source.hlsl"
injection-regex = "hlsl"
file-types = ["hlsl", "vert", "tesc", "tese", "geom", "frag", "comp" ]
comment-tokens = "//"
block-comment-tokens = { start = "/*", end = "*/" }
indent = { tab-width = 4, unit = "    " }
language-servers = [ "shader-language-server" ]

[[grammar]]
name = "hlsl"
source = { git = "https://github.com/tree-sitter-grammars/tree-sitter-hlsl", rev = "bab9111922d53d43668fabb61869bec51bbcb915" }
